### ISSUE TITLE
I stock in login page when I use Udeler

### ISSUE THREAD

**Issue by noamangg** [dnshko/Udeler-clone#3]
I stock in login page when I use it when I press login it opens a new window then I login into my Udemy account put nothing happened
it opens like this
![Screenshot (171)](https://user-images.githubusercontent.com/71488276/148113864-21af72c7-f964-472e-8d18-b200712f924d.png)

**Comment by heliomarpm** [comment]
This entire project is updated here.
https://github.com/heliomarpm/udemy-downloader-gui
